apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "first-initiated-software-template-component"     # set value defined in the (scaffolding/golden path) template
  annotations:
    github.com/project-slug: maarten-dev-hub-training-organization/first-initiated-software-template
spec:
  type: service
  lifecycle: development
  owner: user:default/maarten-vandeperre
