apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "first-initiated-software-template-component"     # set value defined in the (scaffolding/golden path) template
  annotations:
    github.com/project-slug: maarten-dev-hub-training-organization/first-initiated-software-template
    #argocd/app-selector: rht-gitops.com/demo-project=simple-hello-world-service-a
    argocd/app-name: simple-hello-world-service-a
    argocd/instance-name: argoInstance1 # as defined in app-config-rhdh.yaml
spec:
  type: service
  lifecycle: development
  owner: user:default/maarten-vandeperre
